### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by paulxtiseo** [catalin-luntraru/redux-minimal#13]
Anyone converted this starter to Bootstrap 4? What's the known process? I have `npm install`ed `react-bootstrap-4`, changed the CDN link in the `index.html` and changed all the `import` calls. Anything else?

**Comment by catalin-luntraru** [comment]
[react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) is still using bootstrap 3.
[react-bootstrap-4](https://www.npmjs.com/package/react-bootstrap-4) says it's a temporary fork, so I don't think it's production ready.
[reactstrap](https://github.com/reactstrap/reactstrap) seems to be a much stable library for react and bootstrap 4.

The issue here is that [bootstrap 4](https://v4-alpha.getbootstrap.com/) is still in its alpha stages, and you would want to use redux-minimal to build production capable apps.

But I don't see any problem with replacing the boostrap 3 lib with the bootstrap 4 one, especially if you're just trying out things. 

The process should be straight forward, but please let me know if come across any issues.
