### ISSUE TITLE
babel-runtime required as dependency

### ISSUE THREAD

**Issue by Jiraffe7** [catalin-luntraru/redux-minimal#2]
On npm start, faced many errors regarding babel-runtime.

Read from the site below that babel-runtime is required as dependency.
http://babeljs.io/docs/plugins/transform-runtime/

After installing, there are no more errors.

**Comment by catalin-luntraru** [comment]
Have you installed the app using the steps from the Getting started section of the readme https://github.com/catalin-luntraru/redux-minimal#getting-started ?

Try running "npm list -g" and if you have any globals installed, try to uninstall them with "npm uninstall -g <package>". And then try again by deleting the node_modules folder and then run "npm install". Normally you don't need babel-runtime, because we already have babel-plugin-transform-runtime.

Can you provide a screenshot with the babel-runtime error?

**Comment by catalin-luntraru** [comment]
Now redux-minimal works with node v4 too.
https://github.com/catalin-luntraru/redux-minimal/commit/84dd963ee6f68ffa473f5d46dbff170a3cc6e216

**Comment by Jiraffe7** [comment]
Yes, I was using node v4. It works now.

Thanks!
