### ISSUE TITLE
Unable to view users app demo due to TypeError: last is undefined

### ISSUE THREAD

**Issue by Jiraffe7** [catalin-luntraru/redux-minimal#3]
When loading the page, it's blank due to an error `TypeError: last is undefined` that references to this segment of code `last.apply(undefined, arguments)` from `bundle.js`:

```javascript
/* 262 */
/***/ function(module, exports) {

	"use strict";

	exports.__esModule = true;
	exports["default"] = compose;
	/**
	 * Composes single-argument functions from right to left. The rightmost
	 * function can take multiple arguments as it provides the signature for
	 * the resulting composite function.
	 *
	 * @param {...Function} funcs The functions to compose.
	 * @returns {Function} A function obtained by composing the argument functions
	 * from right to left. For example, compose(f, g, h) is identical to doing
	 * (...args) => f(g(h(...args))).
	 */

	function compose() {
	  for (var _len = arguments.length, funcs = Array(_len), _key = 0; _key < _len; _key++) {
	    funcs[_key] = arguments[_key];
	  }

	  if (funcs.length === 0) {
	    return function (arg) {
	      return arg;
	    };
	  }

	  if (funcs.length === 1) {
	    return funcs[0];
	  }

	  var last = funcs[funcs.length - 1];
	  var rest = funcs.slice(0, -1);
	  return function () {
	    return rest.reduceRight(function (composed, f) {
	      return f(composed);
	    }, last.apply(undefined, arguments));
	  };
	}
```

**Comment by catalin-luntraru** [comment]
Can you provide the "npm start" message log so I can see what exactly was used to bundle the js file?

**Comment by Jiraffe7** [comment]
Here is the message log:
[output.txt](https://github.com/catalin-luntraru/redux-minimal/files/505833/output.txt)

This is after pulling the latest changes you have made to support node v4.

**Comment by catalin-luntraru** [comment]
Here's my output log file
[output2.txt](https://github.com/catalin-luntraru/redux-minimal/files/505862/output2.txt)

It is a bit different with 12 bundles files less, but I guess that's because I'm on windows and you are on linux.

Can you provide a print screen of the your browser and the console opened with the error? I guess you use chrome right?

Can you see the demo app at http://redux-minimal-app.catalin-luntraru.com/ ?

This error `TypeError: last is undefined` is very random. There's no variable `last` in the code base, so it must be some dependency failing somewhere, which means the environment is not setup correctly. can you reset your environment with these steps? 

Try to backup all your apps, then uninstall nodejs. Restart your computer so you make sure there are no processes left over running . 
Then remove all the left over files/folders, and then reinstall node v6.7.0 and then copy back your apps (except the redux-minimal one) 
Then try to install redux-minimal following the steps at nr.2 from https://github.com/catalin-luntraru/redux-minimal#getting-started and see if it works.

**Comment by Jiraffe7** [comment]
I have tried using Chrome and Firefox.

Reinstalled node v6.7.0 and redux-minimal but still get the same error.

I get this warning during `npm install`
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Here are the screenshots from both:

Chrome:
![chrome-error-1](https://cloud.githubusercontent.com/assets/7575125/19033889/4dcb51d6-8993-11e6-9b7f-60d2c2581ab1.png)
![chrome-error-2](https://cloud.githubusercontent.com/assets/7575125/19033891/4eff61be-8993-11e6-9357-26019a119140.png)

Firefox:
![firefox-error-1](https://cloud.githubusercontent.com/assets/7575125/19033897/5366b4be-8993-11e6-8295-903bd3609d0f.png)
![firefox-error-2](https://cloud.githubusercontent.com/assets/7575125/19033901/550c4c2a-8993-11e6-9b3b-89da08816cb8.png)

**Comment by catalin-luntraru** [comment]
Ok the issue is with redux compose() which complains that there's no 2nd function.
I was able to replicate the error, when my redux tools were disabled, so this only happens when you don't have the redux tools installed/enabled.
I changed the code in order to work without the redux tools too.
Please checkout the latest git code and see if it works now.

**Comment by Jiraffe7** [comment]
It works now.
Thanks!
