### ISSUE TITLE
Failed at the redux-minimal@1.0.0 start script 'webpack-dev-server --inline --hot --history-api-fallback'

### ISSUE THREAD

**Issue by grimunit** [catalin-luntraru/redux-minimal#4]
Running npm start gives me the following error:

Failed at the redux-minimal@1.0.0 start script 'webpack-dev-server --inline --hot --history-api-fallback'

Attached the npm-debug.log

Was using Node v4.4.3 and NPM v.2.15.1
Also tried with Node v6.7.0 and NPM v.3.10.3

Both gave exact same error after rm -rf node_modules and another npm i

[npm-debug.txt](https://github.com/catalin-luntraru/redux-minimal/files/505501/npm-debug.txt)

**Comment by catalin-luntraru** [comment]
I searched google for that error https://www.google.com/search?q=webpack-dev-server+Returned%3A+code%3A+1+signal%3A+null&oq=webpack-dev-server+Returned%3A+code%3A+1+signal%3A+null and here at https://github.com/webpack/webpack-dev-server/issues/409 the issue was that 8080 was already used. A similar issue here https://github.com/vuejs-templates/webpack/issues/261

Please check if you have only one node running at 8080 and is available, or configure multiple nodes to work correctly.

Please let me know if you managed to make node work.

**Comment by grimunit** [comment]
Hmm ya just tried it on my other laptop and it seems to work fine. I tried doing killall node, and made sure there were no other instances running but it still gives me the same error. But definitely something to do with the way this machine is configured.

I tried changing the port in the webpack.config but it didn't help either.

**Comment by catalin-luntraru** [comment]
Try to backup all your apps, then uninstall nodejs. Restart your computer so you make sure there are no processes left over running . 
Then remove all the left over files/folders, and then reinstall node v6.7.0 and then copy back your apps. 
Then try to install redux-minimal following the steps at nr.2 from https://github.com/catalin-luntraru/redux-minimal#getting-started and see if it works.

**Comment by catalin-luntraru** [comment]
I closed this, since it's not relevant to redux-minimal, but to your environment.
But please do post here if you manage to make your environment work.
